os:
- linux
language: android
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-28
  - android-27
  - sys-img-armeabi-v7a-google_apis-25
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_script:
- cd src/spe_66_days
- openssl aes-256-cbc -K $encrypted_82466cab9446_key -iv $encrypted_82466cab9446_iv -in google-services.json.enc -out android/app/google-services.json -d
- wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
- unzip -qq gradle-3.5-bin.zip
- export GRADLE_HOME=$PWD/gradle-3.5
- export PATH=$GRADLE_HOME/bin:$PATH
- git clone https://github.com/flutter/flutter.git -b beta
- "./flutter/bin/flutter doctor"
script:
- "./flutter/bin/flutter test"
- "./flutter/bin/flutter build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  provider: releases
  api_key:
    secure: Q2RudfydOcvALz/pz30UTL+y7zhCpV4FkcBRmXhep6jkGuFEDHlXJr8UFHhIOA1ORARLgf4Mmr5oO2bVpMmfX+EU+TgjoxQ8/aQwoB8myAliQyu9ge7nC4VA61h42fXqUCKWE4kWgLdTAoIhyNh+dIFZINpoIXDNILgR3fEtcSbWhpFtR6eOwkjsMh/qSwaud7EvlVNYfNxes8e+AltxUYcikUPBuCI1DT15j+7ZsExbAmjwbFhOSxlQzDsHAslsTNTDZI8B6XUDMoNnm8JtiFohey7XkBbK/E7ippuzV19ij5/B63RIjlZ1E8Vbcvg1TvHaQAJFW9fuW3P2kshccQDHfQUvtp5Aqu+Tj1d1vepscAsP9W3dZhwZ8oY/X6hmZ24fpsWBnRQgqaZ5DfOSnYcExYDldMqfsQgkSsFc7s+ba6DXAfSUELE3HVb6HpyzYmwdWT3rGcUaaEz0u1xOfvaLzG8G1/B3MGPfUiKmk8z2fFbk/6vkdbOQquFITmtq6kYjG+a1l9qsSuLIsXlqqXr9km+p9emhaRr6mRUuvN5a/6CdRnVZZTN1SBul5rNAHJHh55HHu0YMauAEJAX9G3LPaVgT3I7hCmzGsHGct3pd+VkMsVoHIRuFrwBm6+evwiarj7+JLHymgyp+mc3O4bMsRInZZu0BuLQx2qkixk4=
  file: build/app/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: simon-wh/66-Days
    tags: true
